"""AntiOS 2.0 Project Manifest Engine.

Defines the canonical project-local AntiOS instance manifest (.antios/manifest.json).
Answers:
"What did I install here, from which AntiOS revision, what does AntiOS own,
what does the project own, and what has become stale?"

Implements strict validation, fail-closed deserialization, and cryptographic
fingerprint tracking.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from enum import Enum
import hashlib
import json
import os
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple, Union

from framework.core.version import ANTIOS_VERSION as CURRENT_ANTIOS_VERSION
from framework.core.version import CURRENT_SCHEMA_VERSION

DEFAULT_MANIFEST_REL_PATH = ".antios/manifest.json"



class InstallationState(str, Enum):
    """State of the AntiOS Project Agent OS installation."""
    UNINSTALLED = "UNINSTALLED"
    PARTIAL = "PARTIAL"
    INSTALLED = "INSTALLED"
    REPAIRING = "REPAIRING"
    UPGRADING = "UPGRADING"
    REMOVED = "REMOVED"
    ERROR = "ERROR"


class AdaptationState(str, Enum):
    """State of project adaptation and intelligence synchronization."""
    UNADAPTED = "UNADAPTED"
    ADAPTED = "ADAPTED"
    STALE = "STALE"
    CONFLICT = "CONFLICT"


class ArtifactOwnership(str, Enum):
    """Ownership tier for an installed or managed artifact."""
    GENERATED = "GENERATED"            # Generated by AntiOS compiler, safe to regenerate if unmodified
    MANAGED = "MANAGED"                # Managed by AntiOS, may incorporate project adaptations
    USER_AUTHORED = "USER_AUTHORED"    # Authored/customized by user, strictly protected against overwrite
    PROJECT_PROTECTED = "PROJECT_PROTECTED"  # Project domain path, strictly immutable to agents
    ANTIOS_IMMUTABLE = "ANTIOS_IMMUTABLE"    # AntiOS core governance, strictly immutable
    EXTERNAL = "EXTERNAL"              # Data belonging outside project (e.g. System B experience store)


@dataclass
class ArtifactRecord:
    """Provenance and ownership record for an artifact in the project."""
    path: str
    ownership: ArtifactOwnership
    sha256: str
    source_revision: str
    generated_at: str
    generator: str = "AntiOS-Project-Boundary-Compiler-v2.0"
    source_template: Optional[str] = None
    evidence: List[str] = field(default_factory=list)
    is_user_modified: bool = False
    is_stale: bool = False
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "path": self.path,
            "ownership": self.ownership.value if isinstance(self.ownership, ArtifactOwnership) else str(self.ownership),
            "sha256": self.sha256,
            "source_revision": self.source_revision,
            "generated_at": self.generated_at,
            "generator": self.generator,
            "source_template": self.source_template,
            "evidence": list(self.evidence),
            "is_user_modified": self.is_user_modified,
            "is_stale": self.is_stale,
            "metadata": dict(self.metadata),
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> ArtifactRecord:
        ownership_val = data.get("ownership", ArtifactOwnership.GENERATED.value)
        try:
            ownership = ArtifactOwnership(ownership_val)
        except ValueError:
            ownership = ArtifactOwnership.MANAGED

        return cls(
            path=str(data.get("path", "")),
            ownership=ownership,
            sha256=str(data.get("sha256", "")),
            source_revision=str(data.get("source_revision", "")),
            generated_at=str(data.get("generated_at", "")),
            generator=str(data.get("generator", "AntiOS-Project-Boundary-Compiler-v2.0")),
            source_template=data.get("source_template"),
            evidence=list(data.get("evidence", [])),
            is_user_modified=bool(data.get("is_user_modified", False)),
            is_stale=bool(data.get("is_stale", False)),
            metadata=dict(data.get("metadata", {})),
        )


@dataclass
class ProjectManifest:
    """Canonical Project Agent OS Manifest (.antios/manifest.json)."""
    antios_version: str = CURRENT_ANTIOS_VERSION
    schema_version: str = CURRENT_SCHEMA_VERSION
    project_fingerprint: str = ""
    source_revision: str = "v2.0.0"
    generated_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    adaptation_state: AdaptationState = AdaptationState.UNADAPTED
    installation_state: InstallationState = InstallationState.UNINSTALLED
    managed_paths: Dict[str, ArtifactRecord] = field(default_factory=dict)
    generated_paths: Dict[str, ArtifactRecord] = field(default_factory=dict)
    user_owned_paths: List[str] = field(default_factory=list)
    protected_paths: List[str] = field(default_factory=lambda: [".agents", ".antios", "antios.config.json"])
    stale_paths: List[str] = field(default_factory=list)
    project_profile_reference: str = ".antios/project_profile.json"
    knowledge_revision: str = "1.0"
    capability_revision: str = "1.0"
    agent_topology_revision: str = "1.0"
    tool_policy_revision: str = "1.0"
    memory_revision: str = "1.0"
    reconciliation_state: Optional[Dict[str, Any]] = None
    metadata: Dict[str, Any] = field(default_factory=dict)

    def validate(self) -> Tuple[bool, List[str]]:
        """Validates manifest integrity. Fails closed on any inconsistency."""
        issues: List[str] = []

        if not self.antios_version or not isinstance(self.antios_version, str):
            issues.append("Manifest missing valid 'antios_version'")
        if not self.schema_version or not isinstance(self.schema_version, str):
            issues.append("Manifest missing valid 'schema_version'")
        if not self.project_fingerprint or not isinstance(self.project_fingerprint, str):
            issues.append("Manifest missing valid 'project_fingerprint'")
        if not self.source_revision or not isinstance(self.source_revision, str):
            issues.append("Manifest missing valid 'source_revision'")
        if not self.generated_at or not isinstance(self.generated_at, str):
            issues.append("Manifest missing valid 'generated_at'")

        if not isinstance(self.managed_paths, dict):
            issues.append("'managed_paths' must be a dictionary")
        if not isinstance(self.generated_paths, dict):
            issues.append("'generated_paths' must be a dictionary")
        if not isinstance(self.user_owned_paths, list):
            issues.append("'user_owned_paths' must be a list")
        if not isinstance(self.protected_paths, list):
            issues.append("'protected_paths' must be a list")
        if not isinstance(self.stale_paths, list):
            issues.append("'stale_paths' must be a list")

        if self.reconciliation_state is not None and not isinstance(self.reconciliation_state, dict):
            issues.append("'reconciliation_state' must be a dictionary or None")

        # Verify all managed paths have records
        for p, rec in self.managed_paths.items():
            if not isinstance(rec, ArtifactRecord):
                issues.append(f"Invalid record type in managed_paths for '{p}'")
            elif not rec.sha256:
                issues.append(f"Missing sha256 for managed artifact '{p}'")

        # Verify all generated paths have records
        for p, rec in self.generated_paths.items():
            if not isinstance(rec, ArtifactRecord):
                issues.append(f"Invalid record type in generated_paths for '{p}'")
            elif not rec.sha256:
                issues.append(f"Missing sha256 for generated artifact '{p}'")

        return (len(issues) == 0, issues)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "antios_version": self.antios_version,
            "schema_version": self.schema_version,
            "project_fingerprint": self.project_fingerprint,
            "source_revision": self.source_revision,
            "generated_at": self.generated_at,
            "adaptation_state": self.adaptation_state.value if isinstance(self.adaptation_state, AdaptationState) else str(self.adaptation_state),
            "installation_state": self.installation_state.value if isinstance(self.installation_state, InstallationState) else str(self.installation_state),
            "managed_paths": {p: rec.to_dict() for p, rec in self.managed_paths.items()},
            "generated_paths": {p: rec.to_dict() for p, rec in self.generated_paths.items()},
            "user_owned_paths": list(self.user_owned_paths),
            "protected_paths": list(self.protected_paths),
            "stale_paths": list(self.stale_paths),
            "project_profile_reference": self.project_profile_reference,
            "knowledge_revision": self.knowledge_revision,
            "capability_revision": self.capability_revision,
            "agent_topology_revision": self.agent_topology_revision,
            "tool_policy_revision": self.tool_policy_revision,
            "memory_revision": self.memory_revision,
            "reconciliation_state": dict(self.reconciliation_state) if isinstance(self.reconciliation_state, dict) else None,
            "metadata": dict(self.metadata),
        }

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def migrate_manifest_data(cls, data: Dict[str, Any]) -> Tuple[Dict[str, Any], bool]:
        """Migrates older manifest dictionary structures to current schema version."""
        if not isinstance(data, dict):
            raise ValueError(f"Expected dict for ProjectManifest, got {type(data).__name__}")
        migrated = dict(data)
        was_migrated = False

        schema_v = str(migrated.get("schema_version", ""))
        if not schema_v:
            migrated["schema_version"] = CURRENT_SCHEMA_VERSION
            was_migrated = True

        for k in ("managed_paths", "generated_paths"):
            if k not in migrated or not isinstance(migrated[k], dict):
                migrated[k] = {}
                was_migrated = True
        for k in ("user_owned_paths", "protected_paths", "stale_paths"):
            if k not in migrated or not isinstance(migrated[k], list):
                migrated[k] = []
                was_migrated = True
        if "metadata" not in migrated or not isinstance(migrated["metadata"], dict):
            migrated["metadata"] = {}
            was_migrated = True
        if "reconciliation_state" not in migrated:
            migrated["reconciliation_state"] = None

        return migrated, was_migrated

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> ProjectManifest:
        """Constructs ProjectManifest from dict with fail-closed validation."""
        if not isinstance(data, dict):
            raise ValueError(f"Expected dict for ProjectManifest, got {type(data).__name__}")
        data, _ = cls.migrate_manifest_data(data)

        # Extract states safely
        inst_val = data.get("installation_state", InstallationState.UNINSTALLED.value)
        try:
            inst_state = InstallationState(inst_val)
        except ValueError:
            inst_state = InstallationState.ERROR

        adapt_val = data.get("adaptation_state", AdaptationState.UNADAPTED.value)
        try:
            adapt_state = AdaptationState(adapt_val)
        except ValueError:
            adapt_state = AdaptationState.CONFLICT

        # Parse managed paths
        managed_paths: Dict[str, ArtifactRecord] = {}
        for p, rec_data in data.get("managed_paths", {}).items():
            if isinstance(rec_data, dict):
                managed_paths[p] = ArtifactRecord.from_dict(rec_data)

        # Parse generated paths
        generated_paths: Dict[str, ArtifactRecord] = {}
        for p, rec_data in data.get("generated_paths", {}).items():
            if isinstance(rec_data, dict):
                generated_paths[p] = ArtifactRecord.from_dict(rec_data)

        manifest = cls(
            antios_version=str(data.get("antios_version", CURRENT_ANTIOS_VERSION)),
            schema_version=str(data.get("schema_version", CURRENT_SCHEMA_VERSION)),
            project_fingerprint=str(data.get("project_fingerprint", "")),
            source_revision=str(data.get("source_revision") or "v2.0.0"),
            generated_at=str(data.get("generated_at") or datetime.now(timezone.utc).isoformat()),
            adaptation_state=adapt_state,
            installation_state=inst_state,
            managed_paths=managed_paths,
            generated_paths=generated_paths,
            user_owned_paths=list(data.get("user_owned_paths", [])),
            protected_paths=list(data.get("protected_paths", [".agents", "framework", "antios.config.json"])),
            stale_paths=list(data.get("stale_paths", [])),
            project_profile_reference=str(data.get("project_profile_reference", ".antios/project_profile.json")),
            knowledge_revision=str(data.get("knowledge_revision", "1.0")),
            capability_revision=str(data.get("capability_revision", "1.0")),
            agent_topology_revision=str(data.get("agent_topology_revision", "1.0")),
            tool_policy_revision=str(data.get("tool_policy_revision", "1.0")),
            memory_revision=str(data.get("memory_revision", "1.0")),
            reconciliation_state=data.get("reconciliation_state") if isinstance(data.get("reconciliation_state"), dict) else None,
            metadata=dict(data.get("metadata", {})),
        )

        is_valid, issues = manifest.validate()
        if not is_valid:
            raise ValueError(f"ProjectManifest validation failed: {'; '.join(issues)}")

        return manifest

    @classmethod
    def from_json(cls, json_str: str) -> ProjectManifest:
        """Parses JSON string into ProjectManifest. Fails closed on invalid JSON."""
        try:
            data = json.loads(json_str)
        except json.JSONDecodeError as e:
            raise ValueError(f"Malformed manifest JSON: {e}")
        return cls.from_dict(data)

    def is_artifact_owned_by_antios(self, rel_path: str) -> bool:
        """Returns True if path is tracked as managed or generated by AntiOS."""
        norm = rel_path.replace("\\", "/").strip("/")
        return norm in self.managed_paths or norm in self.generated_paths

    def is_artifact_user_owned(self, rel_path: str) -> bool:
        """Returns True if path is tracked as user-owned or marked modified."""
        norm = rel_path.replace("\\", "/").strip("/")
        if norm in self.user_owned_paths:
            return True
        if norm in self.managed_paths and self.managed_paths[norm].is_user_modified:
            return True
        if norm in self.generated_paths and self.generated_paths[norm].is_user_modified:
            return True
        return False

    def is_artifact_stale(self, rel_path: str) -> bool:
        """Returns True if path is marked as stale."""
        norm = rel_path.replace("\\", "/").strip("/")
        return norm in self.stale_paths

    @property
    def artifacts(self) -> Dict[str, ArtifactRecord]:
        """Unified dictionary of all managed and generated artifacts."""
        res = dict(self.managed_paths)
        res.update(self.generated_paths)
        return res


def load_manifest(target_root: Union[str, Path]) -> Optional[ProjectManifest]:
    """Loads .antios/manifest.json from target directory or direct file path. Returns None if missing."""
    p = Path(target_root)
    if p.is_file() and p.name.endswith(".json"):
        target_path = p
    else:
        target_path = p / DEFAULT_MANIFEST_REL_PATH

    if not target_path.is_file():
        return None
    try:
        content = target_path.read_text(encoding="utf-8")
        return ProjectManifest.from_json(content)
    except Exception as e:
        # Fail closed on corrupted manifest
        raise ValueError(f"Corrupted or invalid AntiOS manifest at '{target_path}': {e}")


def save_manifest(manifest: ProjectManifest, target_root: Union[str, Path]) -> Path:
    """Saves ProjectManifest to target directory with directory creation and validation."""
    is_valid, issues = manifest.validate()
    if not is_valid:
        raise ValueError(f"Cannot save invalid manifest: {'; '.join(issues)}")

    target_path = Path(target_root) / DEFAULT_MANIFEST_REL_PATH
    target_path.parent.mkdir(parents=True, exist_ok=True)
    target_path.write_text(manifest.to_json(indent=2), encoding="utf-8", newline="\n")
    return target_path
