"""
AntiOS 3.0 Project Environment Compiler — Safe Artifact Emitter

Handles safe, deterministic, idempotent emission of compiler output artifacts:
- .agents/routes.json
- AGENTS.md (Turn-0 Constitution, strictly bounded to <= 40 lines, < 250 tokens)
- .agents/cache/ast_outlines.json

Preserves user-authored files from destructive overwriting and enforces LF line endings.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from .project_model import ProjectModel

CANONICAL_SIGNATURE = "<!-- Generated by AntiOS Project Compiler -->"


@dataclass
class EmissionRecord:
    path: str  # POSIX relative path
    action: str  # "created", "overwritten", "skipped", "preserved", "check_only"
    bytes_written: int = 0
    warning: Optional[str] = None


class ArtifactEmitter:
    """Safely emits canonical JSON and bounded AGENTS.md artifacts into the target project."""

    def __init__(self, project_root: Path, check_mode: bool = False, force: bool = False):
        self.project_root = project_root.resolve()
        self.check_mode = check_mode
        self.force = force
        self.records: List[EmissionRecord] = []

    def emit_json(self, rel_path: str, data: Dict[str, Any]) -> EmissionRecord:
        """Write formatted canonical JSON with stable keys, 2-space indent, and LF newline."""
        content = json.dumps(data, indent=2, sort_keys=True, ensure_ascii=False) + "\n"
        encoded = content.encode("utf-8")
        target = self.project_root / rel_path

        if self.check_mode:
            record = EmissionRecord(
                path=rel_path,
                action="check_only",
                bytes_written=len(encoded),
            )
            self.records.append(record)
            return record

        try:
            target.parent.mkdir(parents=True, exist_ok=True)
            action = "overwritten" if target.exists() else "created"
            with open(target, "wb") as f:
                f.write(encoded)
            record = EmissionRecord(path=rel_path, action=action, bytes_written=len(encoded))
        except OSError as e:
            record = EmissionRecord(path=rel_path, action="failed", warning=str(e))

        self.records.append(record)
        return record

    def emit_agents_md(
        self,
        project_model: ProjectModel,
        routes_doc: Dict[str, Any],
    ) -> Tuple[EmissionRecord, str]:
        """
        Generate and emit the compact Turn-0 AGENTS.md.
        Enforces:
        - <= 40 lines
        - < 250 tokens
        - User-authored conflict protection: if user-authored without signature and not --force,
          emits AGENTS.generated.md instead and raises a warning.
        """
        content = self._generate_agents_md_content(project_model, routes_doc)
        lines = content.strip().split("\n")
        line_count = len(lines)

        # Estimate tokens (standard approximation ~1.3 tokens per word)
        word_count = len(content.split())
        token_estimate = int(word_count * 1.3)

        target_name = "AGENTS.md"
        target_path = self.project_root / target_name
        warning_msg = None

        # Ownership protection check
        if target_path.is_file():
            try:
                existing = target_path.read_text(encoding="utf-8", errors="ignore")
                is_generated = CANONICAL_SIGNATURE in existing
                if not is_generated and not self.force:
                    # Protect user-authored content!
                    target_name = "AGENTS.generated.md"
                    target_path = self.project_root / target_name
                    warning_msg = (
                        "Existing AGENTS.md appears user-authored (missing signature). "
                        "Emitted AGENTS.generated.md instead to preserve user content. "
                        "Use --force to overwrite."
                    )
            except Exception:
                pass

        encoded = content.encode("utf-8")

        if self.check_mode:
            record = EmissionRecord(
                path=target_name,
                action="check_only",
                bytes_written=len(encoded),
                warning=warning_msg,
            )
            self.records.append(record)
            return record, content

        try:
            action = "overwritten" if target_path.exists() else "created"
            with open(target_path, "wb") as f:
                f.write(encoded)
            record = EmissionRecord(
                path=target_name,
                action=action,
                bytes_written=len(encoded),
                warning=warning_msg,
            )
        except OSError as e:
            record = EmissionRecord(path=target_name, action="failed", warning=str(e))

        self.records.append(record)
        return record, content

    def _generate_agents_md_content(
        self,
        model: ProjectModel,
        routes_doc: Dict[str, Any],
    ) -> str:
        """Constructs strictly bounded AGENTS.md markdown content."""
        subsystems = routes_doc.get("subsystems", {})
        sorted_names = sorted(subsystems.keys())

        # Determine main test command
        test_cmd_str = "python tests/run_all.py"
        if subsystems:
            first_sub = next(iter(subsystems.values()))
            if "test_suite" in first_sub and first_sub["test_suite"]:
                test_cmd_str = " ".join(first_sub["test_suite"][:3])

        lines: List[str] = [
            CANONICAL_SIGNATURE,
            f"# {model.project_id}",
            "",
            "AntiOS 3.0 Agent-Native Environment & Governance Plane.",
            "",
            "## Turn-0 Orientation",
            "- **Route Map**: Read `.agents/routes.json` before searching to locate authoritative code.",
            f"- **Verification Law**: Run `{test_cmd_str}` before completing. Exit code must be 0.",
            "- **Protected Boundaries**: `.agents/`, `antios.config.json`, `.git/`. No uncoordinated edits.",
            "- **Core Invariants**: Fail-Closed (`INV-04`), Maker-Checker (`INV-05`), 4-Zone Boundary (`INV-10`).",
            "",
            "## Subsystem Index",
            "| Subsystem | Root Directory | Entrypoint |",
            "| :--- | :--- | :--- |",
        ]

        # Limit index table rows to at most 6 to guarantee strict line budget
        display_subsystems = sorted_names[:6]
        for s_name in display_subsystems:
            info = subsystems[s_name]
            root_dir = info.get("root_dir", s_name)
            entrypoint = info.get("entrypoint", "")
            lines.append(f"| `{s_name}` | `{root_dir}` | `{entrypoint}` |")

        lines.extend([
            "",
            "## Wayfinding",
            "Consult `.agents/routes.json` for complete capability lists and proving test commands.",
            "",
        ])

        return "\n".join(lines)
